### ISSUE TITLE
JS Platform

### ISSUE THREAD

**Issue by galex** [PocketByte/LocoLaser#5]
Hello,

Do you plan on supporting JS targets as well?

Regards,
Alex

**Comment by KamiSempai** [comment]
Hello.
I'm not so familiar with JS to be sure that will do it in the right way. But I would do it. If you show me how will look JS implementation for following example: https://github.com/PocketByte/locolaser-kotlin-mpp-example, I will try to do it soon as posible.

**Comment by SimonSchubert** [comment]
It's a cool project, thanks, I might try it out in my android/ios mpp project. And I'm also interested in the js target and even more in the desktop(linux/osx/windows) target.

**Comment by KamiSempai** [comment]
> It's a cool project, thanks, I might try it out in my android/ios mpp project. And I'm also interested in the js target and even more in the desktop(linux/osx/windows) target.

I'm looking on `i18next` as a JS library for localization. But faced with the problem with plurals.
I tried to repeat example from following page https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals but instead of expected translations I get wrong results https://jsfiddle.net/2ro70evu/

For OSX you could use iOS implementation cause they both use same Framework for localization. Linux and Windows not in plans right now but if you provide clear implementation for them I will implement corresponded code generator.

**Comment by KamiSempai** [comment]
JS support was implemented here is an example https://github.com/PocketByte/locolaser-kotlin-mpp-example
